import os
import json
from dotenv import load_dotenv
from groq import Groq
import re
import statistics


# Load environment variables
load_dotenv()

# Initialize Groq client
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def signal_1_llm(text: str) -> float:
    """
    Evaluates text using Groq to determine if it's AI or Human.
    Returns a float between 0.0 (Human) and 1.0 (AI).
    """
    prompt = f"""
    You are an expert stylometric analyst. Analyze the following text and determine the probability that it was generated by an AI.
    Look for semantic coherence, emotional tone, and common AI tropes (predictable transitions, overly formal structure).
    
    Respond ONLY with a valid JSON object containing a single key "ai_probability" with a float value between 0.0 (completely human) and 1.0 (completely AI). Do not include any other text or markdown formatting.

    Text to analyze:
    "{text}"
    """

    try:
        response = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.0, # Keep it deterministic
            response_format={"type": "json_object"}
        )
        
        # Parse the JSON response
        result = json.loads(response.choices[0].message.content)
        return float(result.get("ai_probability", 0.5))
        
    except Exception as e:
        print(f"Error in Groq signal: {e}")
        return 0.5 # Neutral fallback on failure



def signal_2_stylometrics(text: str) -> float:
    """
    Evaluates text structure by calculating sentence length variance (burstiness) 
    and vocabulary diversity (Type-Token Ratio).
    Returns a float between 0.0 (Likely Human) and 1.0 (Likely AI).
    """
    # 1. Clean and parse the text
    words = re.findall(r'\b\w+\b', text.lower())
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    # Fallback if the text is too short to analyze
    if len(words) == 0 or len(sentences) < 2:
        return 0.5 

    # 2. Metric A: Type-Token Ratio (TTR)
    # High TTR = Human (lots of unique words). Low TTR = AI (repetitive vocabulary).
    unique_words = set(words)
    ttr = len(unique_words) / len(words)
    
    # Map TTR to 0.0-1.0 (Roughly: > 0.8 is human, < 0.4 is AI)
    ttr_score = max(0.0, min(1.0, (0.8 - ttr) / 0.4))

    # 3. Metric B: Sentence Length Variance (Burstiness)
    # Human writing mixes short and long sentences. AI stays uniform.
    word_counts = [len(s.split()) for s in sentences]
    variance = statistics.variance(word_counts) if len(sentences) > 1 else 0
    
    # Map variance to 0.0-1.0 (High variance > 30 is human, low < 5 is AI)
    variance_score = max(0.0, min(1.0, (30 - variance) / 25))

    # 4. Combine the two stylometric metrics equally
    stylo_score = (ttr_score * 0.5) + (variance_score * 0.5)
    
    return round(stylo_score, 2)



# --- ISOLATION TEST ---
if __name__ == "__main__":
    test_human = "Man, I cannot believe how tired I am today. The coffee machine broke and my boss is being super annoying about the Q3 reports."
    test_ai = "In conclusion, it is important to note that maintaining a healthy work-life balance is crucial for long-term productivity and overall well-being."
    
    print(f"Human Test Score: {signal_1_llm(test_human)}")
    print(f"AI Test Score: {signal_1_llm(test_ai)}")